# Generated by Django 5.2.9 on 2026-01-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('loyalty_points', models.IntegerField(db_index=True, default=0)),
                ('total_spent', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12)),
                ('last_visit', models.DateField(blank=True, db_index=True, null=True)),
                ('visit_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers_customer',
                'ordering': ['-loyalty_points', '-total_spent'],
            },
        ),
    ]
