# Generated by Django 5.2.9 on 2026-01-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhân viên')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('role', models.CharField(choices=[('manager', 'Quản lý'), ('cashier', 'Thu ngân'), ('chef', 'Đầu bếp'), ('waiter', 'Phục vụ'), ('janitor', 'Vệ sinh')], max_length=20, verbose_name='Chức vụ')),
                ('salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương')),
                ('hire_date', models.DateField(verbose_name='Ngày vào làm')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staff_staff',
                'ordering': ['-created_at'],
            },
        ),
    ]
