targetNamespace: ""
parameters: {}
packages:
  - name: restaurant  # Tên folder nằm trong 'packages/'
    actions:
      - name: auth_service    # Tên folder nằm trong 'restaurant/'
        runtime: python:default
        web: true
        parameters:
          MONGO_URL: "mongodb+srv://..." # Điền connection string của bạn vào đây
          DB_NAME: "auth_db"
          JWT_SECRET: "secret"