name: restaurant-erp
region: sgp

# Using Docker Hub images from hoangtranminhduc
# Using existing DigitalOcean Managed Database:
# Host: restaurant-erp-do-user-28536171-0.e.db.ondigitalocean.com
# Port: 25060, Database: defaultdb, User: doadmin

services:
  # Auth Service
  - name: auth-service
    image:
      registry_type: DOCKER_HUB
      registry: hoangtranminhduc
      repository: restaurant-auth-service
      tag: latest
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api/auth
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        type: SECRET
        value: "django-production-secret-key-x7k2m9n8p5q6r7s8t9u0v1w2"
      - key: DB_HOST
        value: "restaurant-erp-do-user-28536171-0.e.db.ondigitalocean.com"
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_USER
        value: "doadmin"
      - key: DB_PASSWORD
        type: SECRET
        value: "YOUR_ACTUAL_DB_PASSWORD_HERE"
      - key: DB_SSL
        value: "true"
      - key: ALLOWED_HOSTS
        value: "*.ondigitalocean.app"
      - key: REDIS_URL
        value: "redis://localhost:6379/0"

  # Menu Service
  - name: menu-service
    image:
      registry_type: DOCKER_HUB
      registry: hoangtranminhduc
      repository: restaurant-menu-service
      tag: latest
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api/menu
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        type: SECRET
        value: "django-production-secret-key-x7k2m9n8p5q6r7s8t9u0v1w2"
      - key: DB_HOST
        value: "restaurant-erp-do-user-28536171-0.e.db.ondigitalocean.com"
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_USER
        value: "doadmin"
      - key: DB_PASSWORD
        type: SECRET
        value: "YOUR_ACTUAL_DB_PASSWORD_HERE"
      - key: DB_SSL
        value: "true"
      - key: ALLOWED_HOSTS
        value: "*.ondigitalocean.app"

  # Billing Service
  - name: billing-service
    image:
      registry_type: DOCKER_HUB
      registry: hoangtranminhduc
      repository: restaurant-billing-service
      tag: latest
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api/billing
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        type: SECRET
        value: "django-production-secret-key-x7k2m9n8p5q6r7s8t9u0v1w2"
      - key: DB_HOST
        value: "restaurant-erp-do-user-28536171-0.e.db.ondigitalocean.com"
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_USER
        value: "doadmin"
      - key: DB_PASSWORD
        type: SECRET
        value: "YOUR_ACTUAL_DB_PASSWORD_HERE"
      - key: DB_SSL
        value: "true"
      - key: ALLOWED_HOSTS
        value: "*.ondigitalocean.app"

  # Customer Service
  - name: customer-service
    image:
      registry_type: DOCKER_HUB
      registry: hoangtranminhduc
      repository: restaurant-customer-service
      tag: latest
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api/customers
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        type: SECRET
        value: "django-production-secret-key-x7k2m9n8p5q6r7s8t9u0v1w2"
      - key: DB_HOST
        value: "restaurant-erp-do-user-28536171-0.e.db.ondigitalocean.com"
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_USER
        value: "doadmin"
      - key: DB_PASSWORD
        type: SECRET
        value: "YOUR_ACTUAL_DB_PASSWORD_HERE"
      - key: DB_SSL
        value: "true"
      - key: ALLOWED_HOSTS
        value: "*.ondigitalocean.app"

  # Table Service
  - name: table-service
    image:
      registry_type: DOCKER_HUB
      registry: hoangtranminhduc
      repository: restaurant-table-service
      tag: latest
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api/tables
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        type: SECRET
        value: "django-production-secret-key-x7k2m9n8p5q6r7s8t9u0v1w2"
      - key: DB_HOST
        value: "restaurant-erp-do-user-28536171-0.e.db.ondigitalocean.com"
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_USER
        value: "doadmin"
      - key: DB_PASSWORD
        type: SECRET
        value: "YOUR_ACTUAL_DB_PASSWORD_HERE"
      - key: DB_SSL
        value: "true"
      - key: ALLOWED_HOSTS
        value: "*.ondigitalocean.app"

  # Staff Service
  - name: staff-service
    image:
      registry_type: DOCKER_HUB
      registry: hoangtranminhduc
      repository: restaurant-staff-service
      tag: latest
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api/staff
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        type: SECRET
        value: "django-production-secret-key-x7k2m9n8p5q6r7s8t9u0v1w2"
      - key: DB_HOST
        value: "restaurant-erp-do-user-28536171-0.e.db.ondigitalocean.com"
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_USER
        value: "doadmin"
      - key: DB_PASSWORD
        type: SECRET
        value: "YOUR_ACTUAL_DB_PASSWORD_HERE"
      - key: DB_SSL
        value: "true"
      - key: ALLOWED_HOSTS
        value: "*.ondigitalocean.app"

  # Reservation Service
  - name: reservation-service
    image:
      registry_type: DOCKER_HUB
      registry: hoangtranminhduc
      repository: restaurant-reservation-service
      tag: latest
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api/reservations
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        type: SECRET
        value: "django-production-secret-key-x7k2m9n8p5q6r7s8t9u0v1w2"
      - key: DB_HOST
        value: "restaurant-erp-do-user-28536171-0.e.db.ondigitalocean.com"
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_USER
        value: "doadmin"
      - key: DB_PASSWORD
        type: SECRET
        value: "YOUR_ACTUAL_DB_PASSWORD_HERE"
      - key: DB_SSL
        value: "true"
      - key: ALLOWED_HOSTS
        value: "*.ondigitalocean.app"

  # Dashboard Service
  - name: dashboard-service
    image:
      registry_type: DOCKER_HUB
      registry: hoangtranminhduc
      repository: restaurant-dashboard-service
      tag: latest
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api/dashboard
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        type: SECRET
        value: "django-production-secret-key-x7k2m9n8p5q6r7s8t9u0v1w2"
      - key: DB_HOST
        value: "restaurant-erp-do-user-28536171-0.e.db.ondigitalocean.com"
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_USER
        value: "doadmin"
      - key: DB_PASSWORD
        type: SECRET
        value: "YOUR_ACTUAL_DB_PASSWORD_HERE"
      - key: DB_SSL
        value: "true"
      - key: ALLOWED_HOSTS
        value: "*.ondigitalocean.app"
