# Generated by Django 5.2.9 on 2026-01-06 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('original_total', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('table_id', models.IntegerField(blank=True, null=True)),
                ('table_name', models.CharField(blank=True, default='', max_length=50)),
                ('staff_id', models.IntegerField(blank=True, null=True)),
                ('staff_name', models.CharField(blank=True, default='', max_length=100)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('points_used', models.IntegerField(default=0)),
                ('points_discount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_bill',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_id', models.IntegerField(null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill')),
            ],
            options={
                'db_table': 'billing_billitem',
            },
        ),
    ]
